r1 <- DNAStringSet(c(
  "TGCCTTTGCCTCCCAAAGTGCTGGAATTACAGGCATGAGCCACTGAGCCTGGCATGTTATATGCCTTTTTATGCACAAAAGCTCAGAAGGGTCTGCTTTTGAGTACCATTTGGCAGTAGTGAATGATGTGGTTGTGGGAGGAGAACAGGTT",
  "CTCTCACATATGTGATTTAAAAGGTTGAAATTTGCTGGTAACATAAAAAGAGCACTGGACTTAGAACTAAAGGATTTTAATTTGATTCCTGACTGCATACCTTATACAAGTCATTTCCTTGAACTTTGTCTATAAAATGGGAATGGTTATA",
  "CTGTATTTATGTCTGTAGGTCTTTATGTTTATATGTGTCATGATATATCACTACCAAAATATATAAAACAGCTCTAATTATTTGCCTTAAAGGAAATTAACCTCTTACTTCAATTTTTTTTTAGATTAAAACCCAATTCAATTGCTTTTTT",
  "CTCTGTCTCCCAGACTGGAGTGCAGGGGCACAATCTCGGCTCACTTCGACCTCTGCCTCCCCAGTTCAAGTGATTCTCCTGCCTCAGTCTCCTGAGTAGCTGGGATTACAGGAGTGTAGCATGCCTAGCTAATTTTTGTATTTCTAGTAGA",
  "TTCTAAACTGGGCATGGCTTTTAGTGAGAGCCTGGGGCCATCCCAGGCAGCCCAGAAATCCCTGGAATGAGGACTCAGAGATGCATAGTATTAGACATTAGGAAGCCCTTCAGAAATTTTTCAGAATGCTAATTTTTCATACTAGTAGGAA",
  "TTCTTTATGCTGTCTGCTGGTAGCTTCAGTGCATCGTGTGAAACAAAAGTGATGTGAAGAATGTCTTGTAAACATTTCAGTAGATATCCTTGAGAGACAGAAACCCTCTTCTTGCATCACTCACACATGCTCACCTTCTGTTGTCTTCTCA",
  "CTTTTCAGGTAGCCATAGTGTATATTCAGCTTTGGCGATGTCAGCATTTTTCTATCTGCTAATTTCTAGCTGTATGGGACCTTGAGGTAGTCATTTAACTTATCTGTGCTTCAATTTCCTTATCTGTCTACTTAGGACAACAATAGTACCT",
  "CAAATCTGGCTTATTCTAAAAGAGAGTGGAGCTCCAGAAGTGGATGCTTAACGTCACATCCCTAAGTTCCCCCAAGAGCTTTGCTTCTTTTGCCCTCCTCTGCTGGGAGCTGTAGGCAGGAGGCTGGAGGGAGAAGAGTGGTATCAGCGTC",
  "CTTTATCCTTTGGGTATATTACAGATCTATTCATAATTCCAATAGCATTTCCATGCAATATTGTAATGTGTCTATTTATGAATCAATCTCCTCAATCTGAATCTGGGAATGTCTCAAAGTGGAAACCAAATTAACTCTTTATTGGGTATCC",
  "TACTGTAATCCCAGCTACTTGTGAGGCTGAGGTGGGAGGATCATTTGAACCTGGGAGGCAGAGGCTGCAGTGAGCCAAGATCACACCACTGCACTCCAGCCTGGGCGACAGAGCAAGACTGTGCCTCAAAAAAAAAAAAAAAAAAAGAAAG"
))

names(r1) <- letters[seq(1, length(r1), 1)]
reads <- r2
reads <- r1
marker <- reverseComplement(DNAStringSet(c("ACATATGACAACTCAATTAAAC")))
percentID <- 0.95

nuc4.4 <- matrix(c(
  5L, -4L, -4L, -4L, -4L, 1L, 1L, -4L, -4L, 1L, -4L, -1L, -1L, -1L, -2L, -4L, 
  5L, -4L, -4L, -4L, 1L, -4L, 1L, 1L, -4L, -1L, -4L, -1L, -1L, -2L, -4L, -4L, 
  5L, -4L, 1L, -4L, 1L, -4L, 1L, -4L, -1L, -1L, -4L, -1L, -2L, -4L, -4L, -4L, 
  5L, 1L, -4L, -4L, 1L, -4L, 1L, -1L, -1L, -1L, -4L, -2L, -4L, -4L, 1L, 1L, 
  -1L, -4L, -2L, -2L, -2L, -2L, -1L, -1L, -3L, -3L, -1L, 1L, 1L, -4L, -4L, -4L, 
  -1L, -2L, -2L, -2L, -2L, -3L, -3L, -1L, -1L, -1L, 1L, -4L, 1L, -4L, -2L, -2L, 
  -1L, -4L, -2L, -2L, -3L, -1L, -3L, -1L, -1L, -4L, 1L, -4L, 1L, -2L, -2L, -4L, 
  -1L, -2L, -2L, -1L, -3L, -1L, -3L, -1L, -4L, 1L, 1L, -4L, -2L, -2L, -2L, -2L, 
  -1L, -4L, -1L, -3L, -3L, -1L, -1L, 1L, -4L, -4L, 1L, -2L, -2L, -2L, -2L, -4L, 
  -1L, -3L, -1L, -1L, -3L, -1L, -4L, -1L, -1L, -1L, -1L, -3L, -3L, -1L, -1L, 
  -3L, -1L, -2L, -2L, -2L, -1L, -1L, -4L, -1L, -1L, -1L, -3L, -1L, -3L, -3L, 
  -1L, -2L, -1L, -2L, -2L, -1L, -1L, -1L, -4L, -1L, -3L, -1L, -3L, -1L, -3L, 
  -1L, -2L, -2L, -1L, -2L, -1L, -1L, -1L, -1L, -4L, -3L, -1L, -1L, -3L, -1L, 
  -3L, -2L, -2L, -2L, -1L, -1L, -2L, -2L, -2L, -2L, -1L, -1L, -1L, -1L, -1L, 
  -1L, -1L, -1L, -1L, -1L, -1L), 
  nrow = 15L, ncol = 15L,
  dimnames =  list(
    c("A", "T", "G", "C", "S", "W", "R", "Y", "K", "M", "B","V", "H", "D", "N"), 
    c("A", "T", "G", "C", "S", "W", "R", "Y", "K", "M", "B", "V", "H", "D", "N")))
submat <- nuc4.4
submat <- banmat()


pw <- pairwiseAlignment(
  DNAStringSet(reads[1], start = 1, end = nchar(marker)+1),
  marker, 
  type = "overlap", 
  substitutionMatrix = submat, 
  gapOpening = 15, 
  gapExtension = 5, 
  scoreOnly = FALSE)

code_dir <- "."
cmdline <- c("test.fasta.gz", "-o", "trimmed.fasta", "-l", "ATGCNNNNTCT", "-r", "ACATATGACAACTCAATTAAAC", "--leadMisMatch", "0", "--overMisMatch", 3, "--collectRandomIDs", "random.fasta", "-c", "2")
args <- parser$parse_args(cmdline)

debug <- c("test.fasta.gz", "-o", "trimmed.fasta", "-r", "ACATATGACAACTCAATTAAAC", "--overMisMatch", "3")
args <- parser$parse_args(debug)
