#' Write fast(a/q) files given Biostrings and ShortRead objects.
#' 
#' @usage write_seq_file(pointer, seqs, seqType, file, compress = FALSE)
#' 
#' @param pointer ShortRead pointer generated by using ShortRead::readFastq().
#' Not required for fasta writing as sequences are already in Biostrings object.
#' @param seqs BioStrings DNAStringSet object generated by trimming from the 
#' pointer object.
#' @param seqType character either "fasta" or "fastq". The format for the 
#' output file.
#' @param file character Output file name to write sequences.
#' @param compress logical Whether to gzip compress the sequence file when 
#' written or leave it uncompressed. Default is FALSE, or uncompressed.
#' @author Christopher Nobles, Ph.D.

write_seq_files <- function(seqs, seqType, file, compress = FALSE){
  packs <- c("Biostrings", "ShortRead")
  packsLoaded <- suppressMessages(sapply(packs, require, character.only = TRUE))
  stopifnot(all(packsLoaded))
  
  if(seqType == "fasta"){
    if(compress){
      if(grepl(".gz$", file)){
        ShortRead::writeFasta(
          seqs, file = file, compress = TRUE, width = max(width(seqs)))    
      }else{
        ShortRead::writeFasta(
          seqs, file = paste0(file, ".gz"), 
          compress = TRUE, width = max(width(seqs)))
      }
    }else{
      ShortRead::writeFasta(
        seqs, file = file, compress = FALSE, width = max(width(seqs)))
    }
  }else{
    if(compress){
      if(grepl(".gz$", file)){
        ShortRead::writeFastq(seqs, file = file, compress = TRUE)
      }else{    
        ShortRead::writeFastq(seqs, file = paste0(file, ".gz"), compress = TRUE)
      }
    }else{
      ShortRead::writeFastq(
        seqs, file = file, compress = FALSE)
    }
  }
}
