#' Write fast(a/q) files given Biostrings and ShortRead objects.
#' 
#' @usage write_seq_file(pointer, seqs, seqType, file, compress = FALSE)
#' 
#' @param pointer ShortRead pointer generated by using ShortRead::readFastq().
#' Not required for fasta writing as sequences are already in Biostrings object.
#' @param seqs BioStrings DNAStringSet object generated by trimming from the 
#' pointer object.
#' @param seqType character either "fasta" or "fastq". The format for the 
#' output file.
#' @param file character Output file name to write sequences.
#' @param compress logical Whether to gzip compress the sequence file when 
#' written or leave it uncompressed. Default is FALSE, or uncompressed.
#' @author Christopher Nobles, Ph.D.

write_seq_files <- function(pointer, seqs, seqType, file, compress = FALSE){
  packs <- c("Biostrings", "ShortRead")
  packsLoaded <- suppressMessages(sapply(packs, require, character.only = TRUE))
  stopifnot(all(packsLoaded))
  
  if(seqType == "fasta"){
    if(compress){
      writeXStringSet(
        seqs, filepath = paste0(file, ".gz"), compress = TRUE, format = "fasta")
    }else{
      writeXStringSet(
        seqs, filepath = file, compress = FALSE, format = "fasta")
    }
  }else{
    quals <- Biostrings::quality(pointer)
    names(quals@quality) <- ShortRead::id(pointer)
    quals@quality@ranges <- seqs@ranges
    
    if(compress){
      writeXStringSet(
        seqs, filepath = paste0(file, ".gz"), compress = TRUE, 
        format = "fastq", qualities = quals@quality)
    }else{
      writeXStringSet(
        seqs, filepath = file, compress = FALSE, 
        format = "fastq", qualities = quals@quality)
    }
  }
}